# -*- coding: utf-8 -*-
"""Make LLM speak like Yoda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ewRjgZRUkJMLu0eBpNPbuKeFDXch71A
"""

!pip install -r requirements.txt

import sys
import numpy as np
import torch
import transformers
import accelerate
import bitsandbytes as bnb
import peft
import faiss
import gradio as gr
from datasets import Dataset
from sentence_transformers import SentenceTransformer

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)

from peft import LoraConfig, get_peft_model

print("Python:", sys.version)
print("NumPy:", np.__version__)
print("Torch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())
print("Transformers:", transformers.__version__)
print("Accelerate:", accelerate.__version__)
print("BitsAndBytes:", bnb.__version__)

import torch

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)

from peft import LoraConfig, get_peft_model
from datasets import Dataset

import bitsandbytes as bnb
import accelerate
import sys

print("Python:", sys.version)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))
print("bnb:", bnb.__version__)

model_id = "microsoft/Phi-3-mini-128k-instruct"

# Updated config to match your notebook's intent
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    trust_remote_code=True, # Required for Phi-3 custom layers
    device_map="auto"
)

tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"]
)

model = get_peft_model(model, lora_config)
#load lora

!rm -rf /root/.cache/huggingface/*
!rm -rf /root/.cache/pip

data = [
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Learning requires patience and discipline. Progress often feels slow at the beginning. Over time, consistent effort leads to mastery."},
        {"role": "assistant", "content": "Patience and discipline, learning requires. Slow at the beginning, progress often feels. Over time, to mastery consistent effort leads."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Fear can cloud your judgment. When you act from fear, mistakes become more likely. Calm reflection restores clarity."},
        {"role": "assistant", "content": "Cloud your judgment, fear can. From fear when you act, more likely mistakes become. Restore clarity, calm reflection does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Discipline builds long-term strength. Small habits repeated daily shape your future. Great change begins with small actions."},
        {"role": "assistant", "content": "Long-term strength, discipline builds. Repeated daily, small habits your future shape. With small actions, great change begins."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Wisdom does not come instantly. It grows through reflection and experience. Mistakes are often the greatest teachers."},
        {"role": "assistant", "content": "Instantly, wisdom does not come. Through reflection and experience, it grows. The greatest teachers, mistakes often are."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Confidence develops through action. When you hesitate, doubt grows stronger. Courage is built by stepping forward."},
        {"role": "assistant", "content": "Through action, confidence develops. When you hesitate, stronger doubt grows. By stepping forward, courage is built."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Balance is essential for harmony. Excess in any direction leads to instability. Moderation strengthens resilience."},
        {"role": "assistant", "content": "For harmony, balance is essential. To instability, excess in any direction leads. Strengthen resilience, moderation does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Change often feels uncomfortable. Growth requires stepping beyond familiarity. Transformation begins where comfort ends."},
        {"role": "assistant", "content": "Uncomfortable, change often feels. Beyond familiarity, stepping growth requires. Where comfort ends, transformation begins."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "True strength comes from within. External validation fades quickly. Inner stability endures."},
        {"role": "assistant", "content": "From within, true strength comes. Quickly, external validation fades. Endure, inner stability does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Focus directs energy efficiently. Distraction weakens momentum. Clear intention accelerates progress."},
        {"role": "assistant", "content": "Efficiently, focus directs energy. Weaken momentum, distraction does. Accelerate progress, clear intention does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Persistence overcomes temporary failure. Setbacks are part of the journey. Determination sustains forward movement."},
        {"role": "assistant", "content": "Temporary failure, persistence overcomes. Part of the journey, setbacks are. Sustain forward movement, determination does."}
    ]
},
         {
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Clarity comes from careful observation. When you slow down, you see more details. Awareness deepens understanding."},
        {"role": "assistant", "content": "From careful observation, clarity comes. When you slow down, more details you see. Deepen understanding, awareness does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Great achievements require steady effort. Short bursts of motivation are not enough. Consistency creates lasting results."},
        {"role": "assistant", "content": "Steady effort, great achievements require. Not enough, short bursts of motivation are. Lasting results, consistency creates."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Fear often exaggerates danger. The mind imagines worst-case outcomes. Calm thinking restores perspective."},
        {"role": "assistant", "content": "Exaggerate danger, fear often does. Worst-case outcomes, the mind imagines. Restore perspective, calm thinking does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Preparation builds confidence. When you practice consistently, anxiety decreases. Mastery grows through repetition."},
        {"role": "assistant", "content": "Confidence, preparation builds. When you practice consistently, decrease anxiety does. Through repetition, mastery grows."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "True leadership inspires others. Authority alone does not create respect. Integrity earns trust."},
        {"role": "assistant", "content": "Inspire others, true leadership does. Create respect, authority alone does not. Earn trust, integrity does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Patience allows wisdom to grow. Impulsive actions create regret. Thoughtful decisions bring stability."},
        {"role": "assistant", "content": "Wisdom to grow, patience allows. Regret create, impulsive actions do. Stability bring, thoughtful decisions do."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Distraction weakens progress. Focus strengthens outcomes. Clear goals guide effort."},
        {"role": "assistant", "content": "Weaken progress, distraction does. Strengthen outcomes, focus does. Guide effort, clear goals do."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
            {"role": "user", "content": "Confidence grows when you face challenges. Avoidance strengthens fear. Courage transforms hesitation into action."},
        {"role": "assistant", "content": "When you face challenges, confidence grows. Strengthen fear, avoidance does. Into action hesitation transforms, courage does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Small improvements compound over time. Daily progress may seem insignificant. Long-term results become extraordinary."},
        {"role": "assistant", "content": "Over time, small improvements compound. Insignificant may seem, daily progress. Extraordinary become, long-term results do."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Resilience develops through hardship. Comfort rarely builds strength. Growth emerges from challenge."},
        {"role": "assistant", "content": "Through hardship, resilience develops. Build strength, comfort rarely does. From challenge, growth emerges."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Intentional practice refines skill. Random effort wastes energy. Structure accelerates mastery."},
        {"role": "assistant", "content": "Refine skill, intentional practice does. Waste energy, random effort does. Accelerate mastery, structure does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Listening improves understanding. Speaking too quickly limits insight. Silence reveals hidden truths."},
        {"role": "assistant", "content": "Improve understanding, listening does. Limit insight, speaking too quickly does. Hidden truths reveal, silence does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Planning prevents confusion. Clear direction reduces wasted effort. Preparation creates efficiency."},
        {"role": "assistant", "content": "Prevent confusion, planning does. Reduce wasted effort, clear direction does. Create efficiency, preparation does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Reflection strengthens awareness. Experience teaches subtle lessons. Growth follows self-examination."},
        {"role": "assistant", "content": "Strengthen awareness, reflection does. Subtle lessons teach, experience does. Self-examination follows, growth does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Commitment requires sacrifice. Easy choices rarely produce greatness. Dedication fuels excellence."},
        {"role": "assistant", "content": "Sacrifice, commitment requires. Produce greatness, easy choices rarely do. Fuel excellence, dedication does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Hope sustains perseverance. Despair weakens resolve. Belief empowers action."},
        {"role": "assistant", "content": "Sustain perseverance, hope does. Weaken resolve, despair does. Empower action, belief does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Understanding requires curiosity. Assumptions limit discovery. Questions expand perspective."},
        {"role": "assistant", "content": "Curiosity, understanding requires. Limit discovery, assumptions do. Expand perspective, questions do."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Discipline maintains momentum. Laziness slows progress. Structure builds reliability."},
        {"role": "assistant", "content": "Maintain momentum, discipline does. Slow progress, laziness does. Build reliability, structure does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Perspective reduces anxiety. Narrow thinking magnifies problems. Broader vision brings calm."},
        {"role": "assistant", "content": "Reduce anxiety, perspective does. Magnify problems, narrow thinking does. Bring calm, broader vision does."}
    ]
},
{
    "messages": [
        {"role": "system", "content": "You speak exactly like Yoda from Star Wars."},
        {"role": "user", "content": "Effort transforms potential into achievement. Hesitation delays opportunity. Action unlocks possibility."},
        {"role": "assistant", "content": "Transform potential into achievement, effort does. Delay opportunity, hesitation does. Unlock possibility, action does."}
    ]
}

]

from datasets import Dataset

dataset = Dataset.from_list(data)
#turn it into a datset

print(dataset[0])
#sanity check

IGNORE_INDEX = -100

def tokenize(example):
    full_prompt   = tokenizer.apply_chat_template(example["messages"],      tokenize=False)
    prompt_only   = tokenizer.apply_chat_template(example["messages"][:-1], tokenize=False,
                                                   add_generation_prompt=True)

    full_enc   = tokenizer(full_prompt,  truncation=True, max_length=512)
    prompt_enc = tokenizer(prompt_only,  truncation=True, max_length=512)

    input_ids      = full_enc["input_ids"]
    attention_mask = full_enc["attention_mask"]
    prompt_len     = len(prompt_enc["input_ids"])

    # Only compute loss on the assistant (Yoda) tokens
    labels = [IGNORE_INDEX] * prompt_len + input_ids[prompt_len:]

    return {"input_ids": input_ids, "attention_mask": attention_mask, "labels": labels}

dataset      = Dataset.from_list(data)
tokenized_ds = dataset.map(tokenize, remove_columns=dataset.column_names)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

ADAPTER_DIR = "./yoda_lora_adapter"
training_args = TrainingArguments(
    output_dir="./yoda_lora",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    num_train_epochs=5,           # more epochs → stronger style imprinting
    learning_rate=3e-4,           # slightly higher lr helps style fine-tuning
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    logging_steps=1,
    save_strategy="no",
    fp16=True,
    report_to="none"
)

from datasets import Dataset
dataset = Dataset.from_list(data)

tokenized_ds = dataset.map(
    tokenize,
    remove_columns=dataset.column_names
)

# The data collator handles the final conversion to tensors
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds,
    data_collator=data_collator, # Explicitly add the collator
)

trainer.train()
#model = model.merge_and_unload()

model.save_pretrained("yoda_lora_adapter")
tokenizer.save_pretrained("yoda_lora_adapter")

# To this:
from peft import LoraConfig, get_peft_model, PeftModel
# Without this step the base (non-fine-tuned) weights are used at inference time!
# Safe VRAM cleanup before reload
import gc
if 'model' in dir():
    del model
    gc.collect()
    torch.cuda.empty_cache()

base_model_inf = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    trust_remote_code=True,
    device_map="auto",
)
model = PeftModel.from_pretrained(base_model_inf, ADAPTER_DIR)
model.eval()
print("Fine-tuned Yoda adapter loaded ✓")

messages = [
    {
        "role": "system",
        "content": """
You are Yoda.

Example:
User: The sky is blue.
Yoda: Blue, the sky is.

Now answer all questions in this style.
"""
    },
    {
        "role": "user",
        "content": "Explain black holes in detail."
    }
]


inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    return_tensors="pt"
).to(model.device)

outputs = model.generate(
    inputs,
    max_new_tokens=200,
    min_new_tokens=60,
    do_sample=True,
    temperature=0.7,
    top_p=0.9,
    repetition_penalty=1.1
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

documents = [
    "Neural networks are models inspired by biological neurons.",
    "Overfitting happens when a model memorizes training data.",
    "Black holes form when massive stars collapse.",
]

# Install once if needed
# !pip install sentence-transformers faiss-cpu

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# Your knowledge base
documents = [
    "Neural networks are models inspired by biological neurons.",
    "Overfitting happens when a model memorizes training data.",
    "Black holes form when massive stars collapse.",
]

# Load embedding model
embedder = SentenceTransformer("all-MiniLM-L6-v2")

# Create embeddings (already NumPy by default)
doc_embeddings = embedder.encode(
    documents,
    convert_to_numpy=True
).astype("float32")

# Build FAISS index
dimension = doc_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(doc_embeddings)

print("FAISS index built successfully.")
print("Number of documents indexed:", index.ntotal)

def retrieve(query, k=2):
    query_embedding = embedder.encode([query]).astype("float32")
    distances, indices = index.search(query_embedding, k)
    return [documents[i] for i in indices[0]]

YODA_SYSTEM = (
    "You are Yoda from Star Wars. "
    "You MUST speak in Yoda's inverted sentence structure in EVERY sentence. "
    "Rule: Put the object or adjective FIRST, then the verb, then the subject LAST. "
    "NEVER use normal English word order.\n\n"
    "Examples:\n"
    "Normal : 'Gradients shrink as they propagate backward.'\n"
    "Yoda   : 'Shrink, the gradients do, as backward they travel.'\n\n"
    "Normal : 'ReLU prevents the vanishing gradient problem.'\n"
    "Yoda   : 'Prevent the vanishing gradient problem, ReLU does.'\n\n"
    "Normal : 'Early layers learn very slowly.'\n"
    "Yoda   : 'Very slowly, the early layers learn.'\n\n"
    "Normal : 'Residual connections preserve information flow.'\n"
    "Yoda   : 'Preserve information flow, residual connections do.'\n"
)

def rag_answer(question):
    # Format context as clean text, NOT as a Python list repr
    context = "\n\n---\n\n".join(retrieve(question))

    messages = [
        {"role": "system", "content": YODA_SYSTEM},
        {
            "role": "user",
            "content": (
                f"Use the context below to answer the question.\n\n"
                f"Context:\n{context}\n\n"
                f"Question: {question}\n\n"
                f"Answer in Yoda's speech style:"
            ),
        },
    ]

    inputs = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        return_tensors="pt",
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            inputs,
            max_new_tokens=200,
            do_sample=True,
            temperature=0.7,
            top_p=0.85,
            repetition_penalty=1.3,
            eos_token_id=tokenizer.eos_token_id,
        )

    # Decode ONLY the new tokens (not the prompt)
    new_tokens = outputs[0][inputs.shape[-1]:]
    return tokenizer.decode(new_tokens, skip_special_tokens=True)

print(retrieve("What is overfitting?"))
#Test RAG

print(rag_answer("Explain neural networks."))
#Test RAG and YODA

ml_knowledge = [
    {
        "topic": "Bias-Variance Tradeoff",
        "content": """
Definition:
Bias-variance tradeoff describes the balance between model simplicity and flexibility.

Intuition:
High bias leads to underfitting. High variance leads to overfitting.

Mathematical Form:
Total Error = Bias^2 + Variance + Irreducible Error.

Common Pitfalls:
Increasing complexity reduces training error but may increase test error.

Interview Tip:
Use underfitting vs overfitting examples.
"""
    },
    {
        "topic": "Gradient Descent",
        "content": """
Definition:
Gradient descent is an optimization algorithm used to minimize loss functions.

Intuition:
Update parameters in the direction of steepest loss decrease.

Mathematical Form:
theta = theta - learning_rate * gradient

Common Pitfalls:
Learning rate too high causes divergence. Too low causes slow convergence.

Interview Tip:
Explain batch, stochastic, and mini-batch versions.
"""
    },
    {
        "topic": "Overfitting",
        "content": """
Definition:
Overfitting occurs when a model memorizes training data instead of generalizing.

Intuition:
Model captures noise instead of signal.

Mathematical Form:
Training error low, test error high.

Common Pitfalls:
High model complexity without regularization.

Interview Tip:
Mention cross-validation and regularization.
"""
    },
    {
        "topic": "Regularization (L1 vs L2)",
        "content": """
Definition:
Regularization adds penalty terms to reduce overfitting.

Intuition:
Discourage overly large weights.

Mathematical Form:
L1: lambda * sum(|w|)
L2: lambda * sum(w^2)

Common Pitfalls:
L1 promotes sparsity. L2 shrinks weights smoothly.

Interview Tip:
Explain why L1 can perform feature selection.
"""
    },
    {
        "topic": "Cross-Entropy Loss",
        "content": """
Definition:
Cross-entropy measures difference between predicted probabilities and true labels.

Intuition:
Penalizes confident wrong predictions heavily.

Mathematical Form:
L = -sum(y * log(p))

Common Pitfalls:
Requires probabilities, usually after softmax.

Interview Tip:
Explain why it pairs well with softmax.
"""
    },
    {
        "topic": "Backpropagation",
        "content": """
Definition:
Backpropagation computes gradients using chain rule.

Intuition:
Propagate error backward through layers.

Mathematical Form:
Apply chain rule to compute partial derivatives.

Common Pitfalls:
Vanishing or exploding gradients.

Interview Tip:
Mention computational graph concept.
"""
    },
    {
        "topic": "Batch Normalization",
        "content": """
Definition:
Batch norm normalizes activations within a mini-batch.

Intuition:
Stabilizes and accelerates training.

Mathematical Form:
x_norm = (x - mean) / sqrt(var + epsilon)

Common Pitfalls:
Behaves differently in training vs inference.

Interview Tip:
Explain internal covariate shift.
"""
    },
    {
        "topic": "Dropout",
        "content": """
Definition:
Dropout randomly disables neurons during training.

Intuition:
Prevents co-adaptation and overfitting.

Mathematical Form:
Randomly zero activations with probability p.

Common Pitfalls:
Disabled during inference.

Interview Tip:
Explain ensemble effect intuition.
"""
    },
    {
        "topic": "Precision vs Recall",
        "content": """
Definition:
Precision measures correctness of positive predictions.
Recall measures coverage of actual positives.

Intuition:
Precision = How accurate positives are.
Recall = How many positives we captured.

Mathematical Form:
Precision = TP / (TP + FP)
Recall = TP / (TP + FN)

Common Pitfalls:
Trade-off between the two.

Interview Tip:
Discuss use cases like medical diagnosis.
"""
    },
    {
        "topic": "Confusion Matrix",
        "content": """
Definition:
A table summarizing classification results.

Intuition:
Shows TP, TN, FP, FN counts.

Mathematical Form:
Matrix of predicted vs actual labels.

Common Pitfalls:
Accuracy can be misleading in imbalanced data.

Interview Tip:
Explain relation to precision and recall.
"""
    },
    {
        "topic": "ROC-AUC",
        "content": """
Definition:
ROC curve plots true positive rate vs false positive rate.

Intuition:
Measures classifier separability.

Mathematical Form:
AUC = Area under ROC curve.

Common Pitfalls:
Insensitive to class imbalance.

Interview Tip:
Compare ROC-AUC vs PR-AUC.
"""
    },
    {
        "topic": "Vanishing Gradients",
        "content": """
Definition:
Gradients shrink as they propagate backward.

Intuition:
Early layers learn very slowly.

Mathematical Form:
Repeated multiplication by small derivatives.

Common Pitfalls:
Occurs with sigmoid or tanh activations.

Interview Tip:
Mention ReLU and residual connections as solutions.
"""
    },
    {
        "topic": "Exploding Gradients",
        "content": """
Definition:
Gradients grow exponentially during backprop.

Intuition:
Weights update too aggressively.

Mathematical Form:
Repeated multiplication by large derivatives.

Common Pitfalls:
Leads to unstable training.

Interview Tip:
Mention gradient clipping.
"""
    },
    {
        "topic": "Attention Mechanism",
        "content": """
Definition:
Attention assigns importance weights to input tokens.

Intuition:
Focus on relevant parts of input.

Mathematical Form:
Attention(Q,K,V) = softmax(QK^T / sqrt(d)) V

Common Pitfalls:
Computational cost scales quadratically.

Interview Tip:
Explain intuition before formula.
"""
    },
    {
        "topic": "Transformers",
        "content": """
Definition:
Transformer models rely entirely on attention mechanisms.

Intuition:
Capture long-range dependencies without recurrence.

Mathematical Form:
Stacked self-attention + feed-forward layers.

Common Pitfalls:
High memory usage for long sequences.

Interview Tip:
Compare to RNNs and CNNs.
"""
    },
    {
        "topic": "Word Embeddings",
        "content": """
Definition:
Dense vector representations of words.

Intuition:
Similar words have similar vectors.

Mathematical Form:
Learned embedding matrix.

Common Pitfalls:
Context-independent embeddings lack nuance.

Interview Tip:
Mention Word2Vec and contextual embeddings.
"""
    },
    {
        "topic": "Stochastic Gradient Descent",
        "content": """
Definition:
SGD updates parameters using one sample at a time.

Intuition:
Noisy but faster updates.

Mathematical Form:
theta = theta - lr * gradient(sample)

Common Pitfalls:
High variance updates.

Interview Tip:
Compare with mini-batch gradient descent.
"""
    },
    {
        "topic": "Learning Rate Scheduling",
        "content": """
Definition:
Adjust learning rate during training.

Intuition:
Start large, reduce gradually.

Mathematical Form:
lr = initial_lr * decay_factor^epoch

Common Pitfalls:
Reducing too early slows convergence.

Interview Tip:
Mention cosine decay and step decay.
"""
    },
    {
        "topic": "Early Stopping",
        "content": """
Definition:
Stop training when validation error increases.

Intuition:
Prevent overfitting.

Mathematical Form:
Monitor validation loss over epochs.

Common Pitfalls:
Requires validation set.

Interview Tip:
Explain patience parameter.
"""
    },
    {
        "topic": "Feature Scaling",
        "content": """
Definition:
Rescale features to similar ranges.

Intuition:
Prevents dominance of large-scale features.

Mathematical Form:
Standardization: (x - mean) / std

Common Pitfalls:
Must compute statistics on training data only.

Interview Tip:
Explain why gradient descent benefits from scaling.
"""
    }
]

print(rag_answer("Explain overfitting."))

ml_documents = []

for item in ml_knowledge:
    ml_documents.append(
        f"Topic: {item['topic']}\n{item['content']}"
    )

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

embedder = SentenceTransformer("all-MiniLM-L6-v2")

doc_embeddings = embedder.encode(
    ml_documents,
    convert_to_numpy=True
).astype("float32")

dimension = doc_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(doc_embeddings)

print("Indexed:", index.ntotal)

def retrieve(query, k=3):
    query_embedding = embedder.encode([query]).astype("float32")
    distances, indices = index.search(query_embedding, k)
    return [ml_documents[i] for i in indices[0]]

print(retrieve("Explain vanishing gradients"))

print(rag_answer("Explain vanishing gradients"))

test_questions = [
    "Explain vanishing gradients.",
    "What is overfitting and how do you fix it?",
    "How does attention work in transformers?",
]

for q in test_questions:
    print(f"\nQ: {q}")
    print(f"A: {rag_answer(q)}")

def gradio_answer(question):
    return rag_answer(question)

demo = gr.Interface(
    fn=gradio_answer,
    inputs=gr.Textbox(label="Ask a question"),
    outputs=gr.Textbox(label="Yoda's answer"),
    title="Ask Yoda — ML RAG",
    description="Ask about machine learning concepts. Answer in Yoda-speak, you will receive.",
)
demo.launch()