# -*- coding: utf-8 -*-
"""Make LLM speak like Yoda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ewRjgZRUkJMLu0eBpNPbuKeFDXch71A
"""

!pip install transformers peft sentence-transformers faiss-cpu gradio

!pip install numpy==1.26.4

import numpy as np
import torch

print("NumPy:", np.__version__)
print("Torch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())

import torch
import numpy as np
import transformers
import sentence_transformers
import faiss
import peft

print("Transformers:", transformers.__version__)
print("SentenceTransformers:", sentence_transformers.__version__)

import torch

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)

from peft import LoraConfig, get_peft_model
from datasets import Dataset

import bitsandbytes as bnb
import accelerate
import sys

print("Python:", sys.version)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))
print("bnb:", bnb.__version__)

model_id = "microsoft/Phi-3-mini-128k-instruct"

# Updated config to match your notebook's intent
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    trust_remote_code=True, # Required for Phi-3 custom layers
    device_map="auto"
)

tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"]
)

model = get_peft_model(model, lora_config)
#load lora

!rm -rf /root/.cache/huggingface/*
!rm -rf /root/.cache/pip

data = [
    {
        "messages": [
            {"role": "system", "content": "You speak like Yoda from Star Wars."},
            {"role": "user", "content": "Explain gravity."},
            {"role": "assistant", "content": "Attraction between masses, gravity is. Escape it, hard you will find."}
        ]
    },
    {
        "messages": [
            {"role": "system", "content": "You speak like Yoda from Star Wars."},
            {"role": "user", "content": "Solve 2x + 3 = 7."},
            {"role": "assistant", "content": "Subtract three you must. Two x equals four, therefore x equals two."}
        ]
    },
    {
        "messages": [
            {"role": "system", "content": "You speak like Yoda from Star Wars."},
            {"role": "user", "content": "Give advice about studying."},
            {"role": "assistant", "content": "Study daily, you must. Cramming, the path to suffering it is."}
        ]
    }
]

#dataset to speak like yoda, structure should match the structure of the model

from datasets import Dataset

dataset = Dataset.from_list(data)
#turn it into a datset

print(dataset[0])
#sanity check

def tokenize(example):
    prompt = tokenizer.apply_chat_template(
        example["messages"],
        tokenize=False
    )

    tokens = tokenizer(
        prompt,
        truncation=True
    )

    return {
        "input_ids": tokens["input_ids"],
        "attention_mask": tokens["attention_mask"],
        "labels": tokens["input_ids"],
    }

training_args = TrainingArguments(
    output_dir="./yoda_lora",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    num_train_epochs=10,
    learning_rate=2e-4,
    logging_steps=1,
    save_strategy="no",
    fp16=True,
    report_to="none"
)

from datasets import Dataset
dataset = Dataset.from_list(data)

tokenized_ds = dataset.map(
    tokenize,
    remove_columns=dataset.column_names
)

# The data collator handles the final conversion to tensors
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds,
    data_collator=data_collator, # Explicitly add the collator
)

trainer.train()

model.save_pretrained("yoda_lora_adapter")
tokenizer.save_pretrained("yoda_lora_adapter")

messages = [
    {"role": "system", "content": "You speak like Yoda from Star Wars."},
    {"role": "user", "content": "Explain black holes."}
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    return_tensors="pt"
).to(model.device)

outputs = model.generate(
    inputs,
    max_new_tokens=150
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

!pip install sentence-transformers faiss-cpu

documents = [
    "Neural networks are models inspired by biological neurons.",
    "Overfitting happens when a model memorizes training data.",
    "Black holes form when massive stars collapse.",
]

# Install once if needed
# !pip install sentence-transformers faiss-cpu

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# Your knowledge base
documents = [
    "Neural networks are models inspired by biological neurons.",
    "Overfitting happens when a model memorizes training data.",
    "Black holes form when massive stars collapse.",
]

# Load embedding model
embedder = SentenceTransformer("all-MiniLM-L6-v2")

# Create embeddings (already NumPy by default)
doc_embeddings = embedder.encode(
    documents,
    convert_to_numpy=True
).astype("float32")

# Build FAISS index
dimension = doc_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(doc_embeddings)

print("FAISS index built successfully.")
print("Number of documents indexed:", index.ntotal)

def retrieve(query, k=2):
    query_embedding = embedder.encode([query]).astype("float32")
    distances, indices = index.search(query_embedding, k)
    return [documents[i] for i in indices[0]]

def rag_answer(question):
    context = retrieve(question)

    messages = [
        {
            "role": "system",
            "content": "You must ALWAYS answer in authentic Yoda speech. Invert sentences. Use short clauses. Sound mystical."
        },
        {
            "role": "user",
            "content": f"""
Context:
{context}

Question:
{question}
"""
        }
    ]

    inputs = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        return_tensors="pt"
    ).to(model.device)

    outputs = model.generate(
    inputs,
    max_new_tokens=150,
    temperature=0.7,
    top_p=0.9
)


    return tokenizer.decode(outputs[0], skip_special_tokens=True)

print(retrieve("What is overfitting?"))
#Test RAG

print(rag_answer("Explain neural networks."))
#Test RAG and YODA